apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-es
  namespace: nofilio
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store

  target:
    name: postgres
    creationPolicy: Owner

  dataFrom:
  - extract:
      key: /nofilio/postgres

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth0-es
  namespace: nofilio
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store

  target:
    name: auth0
    creationPolicy: Owner

  dataFrom:
  - extract:
      key: /nofilio/auth0
