// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.7
//   protoc               v5.28.2
// source: common.proto

/* eslint-disable */

export const protobufPackage = "identity";

export enum WorkspaceType {
  DEFINED = 0,
  PERSONAL = 1,
  UNRECOGNIZED = -1,
}

export const IDENTITY_PACKAGE_NAME = "identity";
